DROP TABLE IF EXISTS useless;

CREATE TABLE useless
(
    id      INT AUTO_INCREMENT PRIMARY KEY,
    message VARCHAR(250) DEFAULT NULL
);

CREATE TABLE person
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(250) DEFAULT NULL
);